
SET SERVEROUTPUT ON;



DROP TABLE ThongBao CASCADE CONSTRAINTS;
DROP TABLE UngTuyen CASCADE CONSTRAINTS;
DROP TABLE CV CASCADE CONSTRAINTS;
DROP TABLE TinTuyenDung CASCADE CONSTRAINTS;
DROP TABLE SinhVien CASCADE CONSTRAINTS;
DROP TABLE DoanhNghiep CASCADE CONSTRAINTS;
DROP TABLE TaiKhoan CASCADE CONSTRAINTS;

